language: php

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq clamav-daemon
  - sudo freshclam
  - sudo /etc/init.d/clamav-daemon start

before_cache:
  - sudo chown clamav:travis /var/lib/clamav
  - sudo chmod 775 /var/lib/clamav
  
cache:
  directories:
    - $HOME/.composer/cache
    - /var/lib/clamav

install:
  - composer install

php:
  - 5.6
  - 7.0
  - 7.1

script:
  - vendor/bin/phpunit
