language: php

before_install:
  - sudo sh install_clam.sh
  
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/clamav

install:
  - composer install

php:
  - 5.6
  - 7.0
  - 7.1

script:
  - vendor/bin/phpunit
