language: php

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq clamav-daemon
  - sudo freshclam
  - sudo /etc/init.d/clamav-daemon start

php:
  - 5.3
  - 5.4
  - 5.5

script:
  - phpunit