language: php

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq clamav-daemon
  - sudo freshclam
  - sudo /etc/init.d/clamav-daemon start
  
cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install
  - find /etc/clamav -print -exec cat {} \;

php:
  - 5.6
  - 7.0
  - 7.1

script:
  - vendor/bin/phpunit
